#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

class TemplateGallery {
  constructor() {
    this.name = 'template-gallery';
    this.version = '1.0.0';
    this.description = 'Browse and select from starter templates for common project types';
  }

  list() {
    return this._templates().map(t => ({
      id: t.id,
      name: t.name,
      description: t.description,
      category: t.category,
      tags: t.tags,
    }));
  }

  getById(id) {
    return this._templates().find(t => t.id === id) || { error: `Template '${id}' not found.` };
  }

  filter(category) {
    const results = this._templates().filter(
      t => t.category === category || t.tags.includes(category)
    );
    if (results.length === 0) {
      return {
        error: `No templates match '${category}'.`,
        suggestions: [...new Set(this._templates().map(t => t.category))],
      };
    }
    return results;
  }

  scaffold(id, outputDir) {
    const template = this.getById(id);
    if (template.error) return template;

    const dir = outputDir || path.join(process.cwd(), template.id);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    const files = {
      'README.md': `# ${template.name}\n\n${template.description}\n\nGenerated by TemplateGallery.\n`,
      'index.js': `// ${template.name}\n// ${template.description}\n\nconsole.log('Hello from ${template.name}!');\n`,
      '.gitignore': 'node_modules/\n.env\n.DS_Store\n',
    };

    Object.entries(files).forEach(([name, content]) => {
      fs.writeFileSync(path.join(dir, name), content);
    });

    return { success: true, outputDir: dir, files: Object.keys(files), template: template.name };
  }

  _templates() {
    return [
      {
        id: 'node-cli',
        name: 'Node.js CLI',
        description: 'Command-line tool with args parsing',
        category: 'cli',
        tags: ['node', 'cli', 'script'],
      },
      {
        id: 'node-api',
        name: 'Node.js API',
        description: 'REST API server with Express-like pattern',
        category: 'api',
        tags: ['node', 'api', 'server', 'rest'],
      },
      {
        id: 'node-lib',
        name: 'Node.js Library',
        description: 'Reusable library with npm packaging',
        category: 'library',
        tags: ['node', 'lib', 'package'],
      },
      {
        id: 'html-page',
        name: 'HTML Landing Page',
        description: 'Single HTML page with CSS and JS',
        category: 'web',
        tags: ['html', 'css', 'js', 'landing'],
      },
      {
        id: 'js-app',
        name: 'Vanilla JS App',
        description: 'Browser app with modules and bundler config',
        category: 'web',
        tags: ['js', 'browser', 'app'],
      },
      {
        id: 'data-pipeline',
        name: 'Data Pipeline',
        description: 'ETL script with file processing steps',
        category: 'data',
        tags: ['etl', 'data', 'pipeline'],
      },
      {
        id: 'package-json',
        name: 'Package.json',
        description: 'Minimal package.json for any Node project',
        category: 'config',
        tags: ['node', 'config', 'npm'],
      },
    ];
  }

  toJSON() {
    return { name: this.name, version: this.version, description: this.description };
  }
}

module.exports = TemplateGallery;
