version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    groups:
      dev-tooling:
        patterns:
          - 'eslint*'
          - 'jest*'
          - 'prettier*'
          - 'typescript*'
          - 'babel*'
          - '@types/*'
    ignore:
      - dependency-name: 'jest*'
        update-types: ['version-update:semver-major']
