/**
 * Context Manager
 * Implements context hygiene from GSD and vibe-stack handoff mechanism
 */

const fs = require('fs');
const path = require('path');

const HANDOFF_PATH = path.join(process.cwd(), '.vibe', 'handoff.md');

class ContextManager {
  constructor() {
    this.contextStack = [];
    this.currentContext = null;
  }

  /**
   * Write handoff document between layer transitions
   * From GSD: Context stabilization across sessions
   * From vibe-stack: Handoff mechanism
   */
  writeHandoff(fromPhase, toPhase, context) {
    const handoff = {
      from: fromPhase,
      to: toPhase,
      timestamp: new Date().toISOString(),
      context: context,
      artifacts: this.listArtifacts(fromPhase),
      nextSteps: this.getNextSteps(toPhase),
      ironLaws: this.getIronLaws()
    };

    const handoffContent = this.formatHandoff(handoff);
    
    try {
      const dir = path.dirname(HANDOFF_PATH);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      fs.writeFileSync(HANDOFF_PATH, handoffContent);
      return true;
    } catch (error) {
      console.error('Failed to write handoff:', error.message);
      return false;
    }
  }

  /**
   * Format handoff document
   */
  formatHandoff(handoff) {
    return `# Handoff: ${handoff.from} → ${handoff.to}

**Timestamp:** ${handoff.timestamp}
**Layer Transition:** ${handoff.from} → ${handoff.to}

## Context from ${handoff.from}

${handoff.context}

## Artifacts Created

${handoff.artifacts.map(a => `- ${a}`).join('\n')}

## Next Steps for ${handoff.to}

${handoff.nextSteps.map(s => `- ${s}`).join('\n')}

## Iron Laws

${handoff.ironLaws.map(l => `- ${l}`).join('\n')}

---

*Generated by vibe-stack orchestrator*
`;
  }

  /**
   * List artifacts created in a phase
   */
  listArtifacts(phase) {
    const artifactPatterns = {
      think: ['plans/think-*.md'],
      plan: ['plans/plan-*.md'],
      break: ['.gsd/breakdown.md'],
      build: ['lib/**/*.js', 'skills/**/index.js'],
      harness: ['.vibe/harness-results.json'],
      review: ['.vibe/review-*.md'],
      ship: ['package.json'],
      retro: ['.vibe/retro-*.md'],
      learn: ['.vibe/learnings/*.md']
    };

    const patterns = artifactPatterns[phase] || [];
    const artifacts = [];

    for (const pattern of patterns) {
      try {
        const files = this.globFiles(pattern);
        artifacts.push(...files);
      } catch (error) {
        // Ignore glob errors
      }
    }

    return artifacts.length > 0 ? artifacts : ['No artifacts found'];
  }

  /**
   * Simple glob implementation
   */
  globFiles(pattern) {
    const files = [];
    const dir = process.cwd();
    
    try {
      const items = fs.readdirSync(dir, { withFileTypes: true });
      for (const item of items) {
        if (item.isFile() && this.matchPattern(item.name, pattern)) {
          files.push(item.name);
        }
      }
    } catch (error) {
      // Ignore errors
    }
    
    return files;
  }

  /**
   * Simple pattern matching
   */
  matchPattern(filename, pattern) {
    const regex = new RegExp(
      '^' + pattern.replace(/\*/g, '.*').replace(/\?/g, '.') + '$'
    );
    return regex.test(filename);
  }

  /**
   * Get next steps for a phase
   */
  getNextSteps(phase) {
    const nextSteps = {
      think: ['Run /vibe:plan for multi-perspective review'],
      plan: ['Run /vibe:break for task decomposition'],
      break: ['Run /vibe:build for TDD implementation'],
      build: ['Run /vibe:harness for production readiness'],
      harness: ['Run /vibe:review for code review'],
      review: ['Run /vibe:qa for browser testing (if has_ui)'],
      qa: ['Run /vibe:ship for deployment'],
      ship: ['Run /vibe:retro for retrospective'],
      retro: ['Run /vibe:learn for pattern capture'],
      learn: ['Run /vibe:evolve for rule evolution'],
      evolve: ['Pipeline complete!']
    };

    return nextSteps[phase] || ['No next steps defined'];
  }

  /**
   * Get iron laws
   */
  getIronLaws() {
    return [
      'CONTEXT HYGIENE: Between every major layer transition, write a handoff and instruct /clear to reset context',
      'EVIDENCE BEFORE CLAIMING DONE: Never mark a step complete without verifying the artifact exists',
      'COMPLETENESS OVER SPEED: Always prefer full over partial',
      'CONFUSION PROTOCOL: Never guess on architecture, design decisions, or user intent',
      'SYSTEMATIC DEBUGGING: No fix without confirmed root cause'
    ];
  }

  /**
   * Reset context between layers
   * From GSD: Context stabilization
   */
  resetContext() {
    this.contextStack = [];
    this.currentContext = null;
    
    // Clear any temporary files
    const tempFiles = ['.vibe/temp-context.json', '.vibe/temp-state.json'];
    for (const file of tempFiles) {
      try {
        const filePath = path.join(process.cwd(), file);
        if (fs.existsSync(filePath)) {
          fs.unlinkSync(filePath);
        }
      } catch (error) {
        // Ignore errors
      }
    }
  }

  /**
   * Push context to stack
   */
  pushContext(context) {
    this.contextStack.push(this.currentContext);
    this.currentContext = context;
  }

  /**
   * Pop context from stack
   */
  popContext() {
    this.currentContext = this.contextStack.pop();
    return this.currentContext;
  }

  /**
   * Get current context
   */
  getCurrentContext() {
    return this.currentContext;
  }

  /**
   * Read handoff document
   */
  readHandoff() {
    try {
      if (fs.existsSync(HANDOFF_PATH)) {
        const content = fs.readFileSync(HANDOFF_PATH, 'utf8');
        return this.parseHandoff(content);
      }
    } catch (error) {
      console.error('Failed to read handoff:', error.message);
    }
    return null;
  }

  /**
   * Parse handoff document
   */
  parseHandoff(content) {
    const lines = content.split('\n');
    const handoff = {
      from: '',
      to: '',
      timestamp: '',
      context: '',
      artifacts: [],
      nextSteps: []
    };

    for (const line of lines) {
      if (line.startsWith('**Timestamp:**')) {
        handoff.timestamp = line.replace('**Timestamp:**', '').trim();
      } else if (line.startsWith('**Layer Transition:**')) {
        const transition = line.replace('**Layer Transition:**', '').trim();
        const [from, to] = transition.split(' → ');
        handoff.from = from;
        handoff.to = to;
      } else if (line.startsWith('- ')) {
        handoff.artifacts.push(line.substring(2));
      }
    }

    return handoff;
  }
}

module.exports = { ContextManager };
