#!/usr/bin/env node

class Architect {
  constructor() {
    this.name = 'architect';
    this.version = '1.0.0';
    this.description =
      'Decompose specs into RED/GREEN/REFACTOR/VERIFY task units with dependency ordering';
  }

  decompose(spec) {
    if (!spec || !spec.features || spec.features.length === 0) {
      return { tasks: [], milestones: [], warnings: [] };
    }

    const features = spec.features;
    const warnings = [];
    const tasks = [];

    this._detectCircularDependencies(features, warnings);
    const sorted = this._topologicalSort(features, warnings);

    for (const feature of sorted) {
      const baseId = feature.id || `FEAT-${String(features.indexOf(feature) + 1).padStart(3, '0')}`;
      tasks.push({
        id: `${baseId}-RED`,
        featureId: baseId,
        featureName: feature.name,
        type: 'RED',
        description: `Write failing tests for ${feature.name}`,
        complexity: 'small',
      });
      tasks.push({
        id: `${baseId}-GREEN`,
        featureId: baseId,
        featureName: feature.name,
        type: 'GREEN',
        description: `Implement ${feature.name} to pass tests`,
        complexity: 'medium',
      });
      tasks.push({
        id: `${baseId}-REFACTOR`,
        featureId: baseId,
        featureName: feature.name,
        type: 'REFACTOR',
        description: `Refactor ${feature.name} implementation`,
        complexity: 'small',
      });
      tasks.push({
        id: `${baseId}-VERIFY`,
        featureId: baseId,
        featureName: feature.name,
        type: 'VERIFY',
        description: `Verify ${feature.name} against spec`,
        complexity: 'small',
      });
    }

    const milestones = this._groupMilestones(tasks);

    return { tasks, milestones, warnings };
  }

  estimateEffort(tasks) {
    const breakdown = { small: 0, medium: 0, large: 0 };
    for (const task of tasks) {
      if (task.complexity === 'large') breakdown.large += 5;
      else if (task.complexity === 'medium') breakdown.medium += 3;
      else breakdown.small += 1;
    }
    const total = breakdown.small + breakdown.medium + breakdown.large;
    return { total, breakdown };
  }

  detectParallelizable(milestones) {
    const groups = [];
    const milestonesById = {};

    for (let i = 0; i < milestones.length; i++) {
      milestonesById[i] = milestones[i];
    }

    const checked = new Set();
    for (let i = 0; i < milestones.length; i++) {
      if (checked.has(i)) continue;
      const group = [milestones[i]];
      checked.add(i);
      for (let j = i + 1; j < milestones.length; j++) {
        if (checked.has(j)) continue;
        const shareDeps = this._sharesDependencies(milestones[i], milestones[j]);
        if (!shareDeps) {
          group.push(milestones[j]);
          checked.add(j);
        }
      }
      groups.push(group);
    }

    return { groups, parallelCount: groups.length };
  }

  exportForHandoff(decomposition) {
    const { tasks, milestones, warnings } = decomposition;
    const effort = this.estimateEffort(tasks);
    const now = new Date().toISOString();

    let md = '# Handoff\n\n';
    md += '---\n';
    md += `generated: ${now}\n`;
    md += `totalTasks: ${tasks.length}\n`;
    md += `totalMilestones: ${milestones.length}\n`;
    md += `totalEffort: ${effort.total} points\n`;
    md += '---\n\n';

    md += '## Context\n\n';
    md += 'This handoff was generated by the Architect skill from a decomposed spec.\n\n';

    md += '## Decomposition\n\n';
    md += '| Milestone | Tasks |\n';
    md += '|-----------|-------|\n';
    for (let i = 0; i < milestones.length; i++) {
      md += `| Milestone ${i + 1} | ${milestones[i].length} tasks |\n`;
    }
    md += '\n';

    md += '### Task Details\n\n';
    md += '| ID | Feature | Type | Complexity |\n';
    md += '|----|---------|------|------------|\n';
    for (const task of tasks) {
      md += `| ${task.id} | ${task.featureName} | ${task.type} | ${task.complexity} |\n`;
    }
    md += '\n';

    md += '## Acceptance Criteria\n\n';
    md += 'Each task must pass its verification step before the next dependent task begins.\n\n';

    md += '## Quality Gates\n\n';
    md += '- All RED tasks produce failing tests\n';
    md += '- All GREEN tasks pass their tests\n';
    md += '- All REFACTOR tasks maintain green tests\n';
    md += '- All VERIFY tasks confirm spec alignment\n';

    if (warnings.length > 0) {
      md += '\n## Warnings\n\n';
      for (const w of warnings) {
        md += `- ${w}\n`;
      }
      md += '\n';
    }

    md += '---\n';
    md += `**Effort:** ${effort.total} points (${effort.breakdown.small}s + ${effort.breakdown.medium}m + ${effort.breakdown.large}l)\n`;

    return md;
  }

  _detectCircularDependencies(features, warnings) {
    const visited = new Set();
    const inStack = new Set();

    const dfs = (feature, path) => {
      if (inStack.has(feature.id)) {
        const cycle = [...path, feature.id].join(' -> ');
        warnings.push(`circular dependency detected: ${cycle}`);
        return;
      }
      if (visited.has(feature.id)) return;
      visited.add(feature.id);
      inStack.add(feature.id);

      const deps = feature.dependencies || [];
      for (const depId of deps) {
        const depFeature = features.find(f => f.id === depId);
        if (depFeature) {
          dfs(depFeature, [...path, feature.id]);
        }
      }
      inStack.delete(feature.id);
    };

    for (const feature of features) {
      dfs(feature, []);
    }
  }

  _topologicalSort(features, warnings) {
    const adj = {};
    const inDegree = {};
    const featureMap = {};

    for (const f of features) {
      const id = f.id || `FEAT-${String(features.indexOf(f) + 1).padStart(3, '0')}`;
      adj[id] = [];
      inDegree[id] = 0;
      featureMap[id] = f;
    }

    for (const f of features) {
      const id = f.id;
      const deps = f.dependencies || [];
      for (const depId of deps) {
        if (adj[depId]) {
          adj[depId].push(id);
          inDegree[id] = (inDegree[id] || 0) + 1;
        }
      }
    }

    const result = [];
    const queue = features.filter(f => (inDegree[f.id] || 0) === 0);

    while (queue.length > 0) {
      const f = queue.shift();
      result.push(f);
      const neighbors = adj[f.id] || [];
      for (const n of neighbors) {
        inDegree[n]--;
        if (inDegree[n] === 0) {
          const nextFeature = featureMap[n];
          if (nextFeature) queue.push(nextFeature);
        }
      }
    }

    const remaining = features.filter(f => !result.find(r => r.id === f.id));
    for (const r of remaining) {
      if (!warnings.some(w => w.includes(r.id))) {
        warnings.push(
          `Feature ${r.id} (${r.name}) could not be ordered due to dependency constraints`
        );
      }
    }

    return [...result, ...remaining];
  }

  _groupMilestones(tasks) {
    if (tasks.length === 0) return [];

    const milestones = [];
    const targetGroupCount = Math.min(7, Math.max(1, Math.ceil(tasks.length / 5)));
    const tasksPerMilestone = Math.max(3, Math.ceil(tasks.length / targetGroupCount));

    for (let i = 0; i < tasks.length; i += tasksPerMilestone) {
      milestones.push(tasks.slice(i, i + tasksPerMilestone));
    }

    return milestones;
  }

  _sharesDependencies(m1, m2) {
    const m1Deps = new Set();
    for (const task of m1) {
      if (task.featureId) m1Deps.add(task.featureId);
    }
    for (const task of m2) {
      if (m1Deps.has(task.featureId)) return true;
    }
    return false;
  }

  toJSON() {
    return { name: this.name, version: this.version, description: this.description };
  }
}

module.exports = Architect;
