#!/usr/bin/env node

/**
 * Project Wizard - Interactive CLI for generating project specs
 * Usage: node index.js
 * Wraps: inquirer (npm), chalk (npm), ora (npm)
 */

const fs = require('fs');
const path = require('path');
let inquirer;
try {
  inquirer = require('inquirer');
} catch (err) {
  throw new Error(
    `Missing dependency: inquirer. Install it with "npm install inquirer@^8". (${err.message})`
  );
}

const PROJECT_TYPES = [
  { name: 'Web Application (React)', value: 'react-web' },
  { name: 'Web Application (Vue)', value: 'vue-web' },
  { name: 'Web Application (Angular)', value: 'angular-web' },
  { name: 'Mobile App (React Native)', value: 'react-native' },
  { name: 'Mobile App (Flutter)', value: 'flutter' },
  { name: 'API / Backend Service', value: 'api' },
  { name: 'Full-stack Application', value: 'fullstack' },
  { name: 'CLI Tool', value: 'cli' },
  { name: 'Desktop Application', value: 'desktop' },
];

const DEPLOYMENT_TARGETS = [
  { name: 'Vercel / Netlify (JAMstack)', value: 'vercel' },
  { name: 'AWS (EC2, Lambda, ECS)', value: 'aws' },
  { name: 'Google Cloud Platform', value: 'gcp' },
  { name: 'Azure', value: 'azure' },
  { name: 'Docker Container', value: 'docker' },
  { name: 'Heroku', value: 'heroku' },
  { name: 'Self-hosted / VPS', value: 'self-hosted' },
  { name: 'Static hosting only', value: 'static' },
];

const FEATURES = [
  { name: 'User Authentication (OAuth, JWT)', value: 'auth', checked: false },
  { name: 'Database Integration', value: 'database', checked: false },
  { name: 'Real-time Updates (WebSocket)', value: 'realtime', checked: false },
  { name: 'File Upload / Storage', value: 'file-upload', checked: false },
  { name: 'Payment Integration (Stripe)', value: 'payments', checked: false },
  { name: 'Email Notifications', value: 'email', checked: false },
  { name: 'Admin Dashboard', value: 'admin', checked: false },
  { name: 'Search Functionality', value: 'search', checked: false },
  { name: 'Analytics / Tracking', value: 'analytics', checked: false },
  { name: 'Internationalization (i18n)', value: 'i18n', checked: false },
  { name: 'SEO Optimization', value: 'seo', checked: false },
  { name: 'API Integration (3rd party)', value: 'api-integration', checked: false },
];

const DESIGN_PREFERENCES = [
  { name: 'Modern Minimalist', value: 'minimalist' },
  { name: 'Material Design', value: 'material' },
  { name: 'Dark Mode First', value: 'dark' },
  { name: 'Corporate / Enterprise', value: 'corporate' },
  { name: 'Creative / Portfolio', value: 'creative' },
  { name: 'E-commerce Focused', value: 'ecommerce' },
  { name: 'Dashboard / Data-heavy', value: 'dashboard' },
];

const COLOR_SCHEMES = [
  { name: 'Blue / Professional', value: 'blue' },
  { name: 'Green / Growth / Eco', value: 'green' },
  { name: 'Purple / Creative / Tech', value: 'purple' },
  { name: 'Orange / Energetic / Startup', value: 'orange' },
  { name: 'Monochrome / Grayscale', value: 'monochrome' },
  { name: 'Custom / Brand colors', value: 'custom' },
];

async function generateProjectSpec(answers) {
  const template = `# Project Specification

## ${answers.projectName}

### Overview
${answers.description}

### Project Type
**${answers.projectType}**

### Target Platform(s)
${answers.deploymentTargets.join(', ')}

### Tech Stack Preferences
${answers.techPreferences || 'To be determined based on project requirements'}

---

## Features

### Core Functionality
${answers.features.map(f => `- ${f}`).join('\n')}

${
  answers.features.includes('auth')
    ? `### Authentication
- Method: ${answers.authMethod || 'JWT'}
- Providers: ${answers.authProviders || 'Email/Password, Social login'}
`
    : ''
}

${
  answers.features.includes('database')
    ? `### Database
- Type: ${answers.databaseType || 'PostgreSQL'}
- ORM: ${answers.orm || 'Prisma / TypeORM'}
`
    : ''
}

${
  answers.features.includes('realtime')
    ? `### Real-time Features
- Technology: WebSocket / Server-Sent Events
- Use cases: ${answers.realtimeUseCases || 'Live updates, notifications'}
`
    : ''
}

---

## Design

### Visual Style
**${answers.designPreference}**

### Color Scheme
**${answers.colorScheme}**

${
  answers.fonts
    ? `### Typography
- Primary Font: ${answers.fonts}
`
    : ''
}

### Responsive Design
${answers.responsiveDesign ? 'Yes - Mobile-first approach' : 'Standard responsive (desktop-primary)'}

---

## Deployment

### Target Environment(s)
${answers.deploymentTargets.map(d => `- ${d}`).join('\n')}

### CI/CD Requirements
${answers.cicd ? answers.cicd : 'Standard deployment pipeline'}

---

## Additional Information

### Timeline
${answers.timeline || 'To be determined'}

### Budget
${answers.budget || 'Not specified'}

### Constraints
${answers.constraints || 'None specified'}

### Notes
${answers.notes || ''}

---

*Generated by Project Wizard on ${new Date().toISOString()}*
`;

  return template;
}

async function main() {
  console.log('\n🎯 Project Wizard - Generate Your Project Spec\n');
  console.log('Answer a few questions to create a comprehensive PROJECT.md\n');

  try {
    const answers = await inquirer.prompt([
      {
        type: 'input',
        name: 'projectName',
        message: '📝 Project name:',
        validate: input => (input.trim() ? true : 'Project name is required'),
      },
      {
        type: 'input',
        name: 'description',
        message: '📋 Brief description (1-2 sentences):',
        validate: input => (input.trim() ? true : 'Description is required'),
      },
      {
        type: 'list',
        name: 'projectType',
        message: '🎨 What type of project are you building?',
        choices: PROJECT_TYPES,
      },
      {
        type: 'checkbox',
        name: 'features',
        message: '⚡ Select features you need (space to select, enter to confirm):',
        choices: FEATURES,
      },
      {
        type: 'list',
        name: 'designPreference',
        message: '🎨 Design style preference:',
        choices: DESIGN_PREFERENCES,
      },
      {
        type: 'list',
        name: 'colorScheme',
        message: '🌈 Color scheme preference:',
        choices: COLOR_SCHEMES,
      },
      {
        type: 'checkbox',
        name: 'deploymentTargets',
        message: '🚀 Deployment targets (select all that apply):',
        choices: DEPLOYMENT_TARGETS,
      },
      {
        type: 'input',
        name: 'techPreferences',
        message: '💻 Any specific tech stack preferences? (press Enter to skip):',
        default: '',
      },
      {
        type: 'confirm',
        name: 'responsiveDesign',
        message: '📱 Is mobile-first responsive design important?',
        default: true,
      },
      {
        type: 'input',
        name: 'timeline',
        message: '⏰ Expected timeline (press Enter to skip):',
        default: 'TBD',
      },
      {
        type: 'input',
        name: 'budget',
        message: '💰 Budget range (press Enter to skip):',
        default: 'Not specified',
      },
      {
        type: 'input',
        name: 'notes',
        message: '📌 Additional notes or requirements (press Enter to skip):',
        default: '',
      },
    ]);

    // Handle conditional questions based on selected features
    if (answers.features.includes('auth')) {
      const authAnswers = await inquirer.prompt([
        {
          type: 'list',
          name: 'authMethod',
          message: '🔐 Preferred authentication method:',
          choices: [
            { name: 'JWT (JSON Web Tokens)', value: 'JWT' },
            { name: 'Session-based', value: 'session' },
            { name: 'OAuth 2.0', value: 'oauth2' },
            { name: 'Passwordless / Magic link', value: 'passwordless' },
          ],
          default: 'JWT',
        },
        {
          type: 'checkbox',
          name: 'authProviders',
          message: '👤 Social login providers (press Enter to skip):',
          choices: [
            { name: 'Google', value: 'Google' },
            { name: 'GitHub', value: 'GitHub' },
            { name: 'Facebook', value: 'Facebook' },
            { name: 'Twitter/X', value: 'Twitter' },
            { name: 'Apple', value: 'Apple' },
          ],
        },
      ]);
      answers.authMethod = authAnswers.authMethod;
      answers.authProviders = authAnswers.authProviders.length
        ? authAnswers.authProviders.join(', ')
        : 'Email/Password only';
    }

    if (answers.features.includes('database')) {
      const dbAnswers = await inquirer.prompt([
        {
          type: 'list',
          name: 'databaseType',
          message: '🗄️ Database type:',
          choices: [
            { name: 'PostgreSQL (recommended)', value: 'PostgreSQL' },
            { name: 'MySQL', value: 'MySQL' },
            { name: 'MongoDB', value: 'MongoDB' },
            { name: 'SQLite (for small projects)', value: 'SQLite' },
            { name: 'Firebase / Supabase (BaaS)', value: 'baas' },
          ],
          default: 'PostgreSQL',
        },
        {
          type: 'list',
          name: 'orm',
          message: '🔧 ORM preference:',
          choices: [
            { name: 'Prisma (recommended)', value: 'Prisma' },
            { name: 'TypeORM', value: 'TypeORM' },
            { name: 'Sequelize', value: 'Sequelize' },
            { name: 'Drizzle', value: 'Drizzle' },
            { name: 'None / Raw SQL', value: 'none' },
          ],
          default: 'Prisma',
        },
      ]);
      answers.databaseType = dbAnswers.databaseType;
      answers.orm = dbAnswers.orm;
    }

    if (answers.features.includes('realtime')) {
      const realtimeAnswer = await inquirer.prompt([
        {
          type: 'input',
          name: 'realtimeUseCases',
          message: '📡 Real-time use cases (e.g., chat, notifications, live updates):',
          default: 'Live notifications, real-time data sync',
        },
      ]);
      answers.realtimeUseCases = realtimeAnswer.realtimeUseCases;
    }

    console.log('\n⏳ Generating your project specification...\n');

    const spec = await generateProjectSpec(answers);
    const outputPath = path.join(process.cwd(), 'PROJECT.md');

    fs.writeFileSync(outputPath, spec, 'utf8');

    console.log('✅ Project specification generated!\n');
    console.log(`📄 Output: ${outputPath}\n`);
    console.log('Next steps:');
    console.log('  1. Review PROJECT.md');
    console.log('  2. Share it with your AI coding assistant');
    console.log('  3. Start building!\n');
  } catch (error) {
    if (error.isTtyError) {
      console.error('\n❌ Terminal does not support interactive prompts.');
      console.error('Try running with: node index.js < /dev/null or use flags\n');
    } else {
      console.error('\n❌ Error:', error.message);
    }
    process.exit(1);
  }
}

if (require.main === module) main();
const scaffold = generateProjectSpec;
module.exports = {
  main,
  generateProjectSpec,
  scaffold,
  PROJECT_TYPES,
  DEPLOYMENT_TARGETS,
  FEATURES,
};
